### ISSUE TITLE
Refresh textile website

### ISSUE THREAD

**Issue by andrewxhill** [textileio/meta#40]
- [ ] Outline new content that tells the story to new visitors
- [ ] Redesign to help new visitors navigate to the right project of interest (docs, photos, comms channels)
- [ ] Implement static webpage

Adding this here for sprint tracking
