### ISSUE TITLE
IPFS Camp

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/meta#44]
This Epic is used to track all community-related work required for IPFS Camp. This includes:
- [x] Workshop
  - [x] [Proposal + rough outline](https://docs.google.com/document/d/1SFxGrj8F3QPZJpsMMEZx_w0fEVG8Y706TAnb6utd1DE/edit?usp=sharing)
  - [x] Slide-based outline
  - [x] Dry run with PL (scheduled for Thurs, 13th of June)
  - [x] Web and/or mobile demo app
  - [x] Final course slides
- [x] Deep dive
  - [x] Rough draft to be [uploaded here](https://github.com/ipfs/camp/blob/master/DEEP_DIVES/10-ipfs-on-mobile.md)
  - [x] Final organization and delivery
- [x] Lightning talk
- [x] Textile Photos SciFi Fair
  - [x] [Description here](https://github.com/ipfs/camp/blob/master/SCI-FI_FAIR/presenter-textile.md)

**Comment by balupton** [comment]
And IPFS Camp is a wrap!

https://medium.com/textileio/ipfs-camp-2019-the-highlights-and-takeaways-2b3cb4f42513
