### ISSUE TITLE
Photos Release Checklist

### ISSUE THREAD

**Issue by sanderpick** [textileio/meta#47]
### `textileio/go-textile`
- [ ] Threads2 integrated for future compatibility and replicator mode
- [ ] `ipfs-cluster` integrated with the federated cafes
- [ ] Ability to track how much data is being stored per user

### `textileio/photos`
- [ ] Functional camera-roll sync
- [ ] Camera-roll selection and sharing features
- [ ] Ability to sign in with an existing account seed
- [ ] Ability to easy sync with desktop
- [ ] Better analytics
- [ ] Address some of the high impact UI feedback from the user poll **(discussion needed)**

### `textileio/photos-desktop`
- [ ] Ability to sign in with an existing account seed
- [ ] Ability to easy sync with mobile (including settings (i.e., cafes))
- [ ] Download/backup to desktop
- [ ] Conversations vs photos views
- [ ] Bluetooth mobile sync?
